/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../pages/__root'
import { Route as ListImport } from './../pages/list'
import { Route as DetailImport } from './../pages/detail'
import { Route as AboutImport } from './../pages/about'
import { Route as IndexImport } from './../pages/index'
import { Route as RegisterItemIndexImport } from './../pages/RegisterItem/index'

// Create/Update Routes

const ListRoute = ListImport.update({
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const DetailRoute = DetailImport.update({
  path: '/detail',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterItemIndexRoute = RegisterItemIndexImport.update({
  path: '/RegisterItem/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/detail': {
      preLoaderRoute: typeof DetailImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/RegisterItem/': {
      preLoaderRoute: typeof RegisterItemIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  DetailRoute,
  ListRoute,
  RegisterItemIndexRoute,
])

/* prettier-ignore-end */
